services:
  # ---------- API ----------
  - type: web
    name: express-api
    env: docker
    dockerContext: ./api
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        fromDatabase:
          name: netdb
          property: connectionString

  # ---------- FRONTEND ----------
  - type: web
    name: react-frontend
    env: docker
    dockerContext: ./frontend
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 5173
      - key: VITE_API_URL
        value: https://express-api.onrender.com

databases:
  # ---------- POSTGRES ----------
  - name: netdb
    plan: free
    databaseName: netdb
    user: netuser
